### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alagenchev** [grzesiek-galezowski/AutoFixtureGenerator#4]
Hi, Thanks for starting this project. What license is the source code?

**Comment by grzesiek-galezowski** [comment]
Hi,

Thank you for your interest! The project is under MIT. I have not added a LICENSE file (mea culpa - will do this shortly), but there is a badge in the readme that says the license is MIT.

Best regards,
grzesiek

**Comment by grzesiek-galezowski** [comment]
I added the LICENSE.txt file. Also please note that the POM (e.g. http://central.maven.org/maven2/com/github/autofixture/autofixturegenerator/1.0.2/autofixturegenerator-1.0.2.pom) says the license is MIT as well.
